version: '3'

services:
  messagebird-api:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    env_file: 
      - .env
  mongo:
    image: mongo:latest
    expose: 
      - 27017
    ports:
      - "27017:27017"